#:import time time

BoxLayoutKukuk:


<BoxLayoutKukuk>:
    orientation: "vertical"
    canvas.before:
        Rectangle:
            # pos: self.pos
            size: self.size
            source: 'images/roodKleed.jpg'
    
    Label:
        text: "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\n\t\t\t   kukuk   \t\t\t\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
        size_hint: 1, 2
    Label:
        text: time.asctime()
        size_hint: 1, .2

